name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # każdorazowy push do main triggeruje deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd main
          npm ci

      - name: Build
        run: |
          cd main
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main/dist
